### PR TITLE
flask support

### PR DESCRIPTION
**Pull request by davidroeca**
This PR adds flask support and adds the actual file objects to the operations rather than the key names.

Resolves https://github.com/lmcgartland/graphene-file-upload/issues/3 .

Let me know if you have any questions. I have working examples in both flask and django

### CODE REVIEW

**Comment by lmcgartland** [comment]
Hey @davidroeca this looks amazing! I want to add some unit tests to make this project a little more maintainable before releasing (probably as v2, looks like these will be breaking changes). I appreciate you refactoring the project so much more cleanly, looks great!

**Comment by davidroeca** [comment]
Glad to contribute! Would you like me to add a few tests or would you prefer to set up the testing infrastructure first?

The other challenge is how to resolve dependencies and recommend installation. Maybe with extras_require and `pip install graphene_file_upload[flask]`, `pip install graphene_file_upload[django]`, etc?

Just let me know what you prefer here and if you need anything from my side

**Comment by ltromp** [comment]
@davidroeca @lmcgartland Thanks for your amazing work. Is it possible to add a working example of Flask to the documentation. I am trying to implement this in a small flask project, but unsure how to get it working.

**Comment by davidroeca** [comment]
@ltromp I've pushed an example that should run appropriately. Just clone the repo, check out the relevant branch, and follow the README within the flask example. Note that the pre-release of `flask_graphql` is required.

**Pull request closed without merging**
